---
- name: Disable root access via ssh
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: ^#?PermitRootLogin
    line: PermitRootLogin no

- name: Disable password authentication
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: ^#?PasswordAuthentication
    line: PasswordAuthentication no
    
- name: Set port for ssh connection
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: ^#?Port
    line: Port 
  notify: reload service sshd